INSERT INTO users(id,name,weight_kg) VALUES ('11111111-1111-4111-8111-111111111111','Алексей',86.4);

INSERT INTO exercises(name,slug,category,equipment,calorie_class,default_rest_seconds,primary_muscles,secondary_muscles,description,instructions,common_mistakes) VALUES
('Жим штанги лёжа','barbell-bench-press','грудь','Штанга','compound',150,'["Грудные мышцы"]'::jsonb,'["Трицепс","Передняя дельта"]'::jsonb,'Базовый горизонтальный жим для развития силы верхней части тела.','["Лягте на скамью, поставьте стопы на пол и сведите лопатки.","Возьмитесь за гриф чуть шире плеч и снимите штангу со стоек.","Плавно опустите гриф к нижней части груди, удерживая предплечья вертикально.","Выжмите штангу вверх, сохраняя контакт таза со скамьёй."]'::jsonb,'["Отбив грифа от груди","Отрыв таза от скамьи","Слишком широко разведённые локти"]'::jsonb),
('Жим гантелей под углом','incline-dumbbell-press','грудь','Гантели','compound',120,'["Грудные мышцы"]'::jsonb,'["Передняя дельта","Трицепс"]'::jsonb,'Жим на наклонной скамье с независимым движением каждой руки.','["Установите наклон скамьи около 20–35 градусов.","Удерживайте гантели у верхней части груди, сведите лопатки.","Выжмите гантели вверх без удара друг о друга.","Медленно опустите их в комфортную нижнюю точку."]'::jsonb,'["Слишком крутой наклон","Сведение гантелей ударом","Потеря контроля в нижней точке"]'::jsonb),
('Сведение рук в кроссовере','cable-fly','грудь','Блок','isolation',75,'["Грудные мышцы"]'::jsonb,'["Передняя дельта"]'::jsonb,'Изолированное сведение рук с постоянным сопротивлением блока.','["Установите рукояти на уровне груди и сделайте шаг вперёд.","Слегка согните локти и зафиксируйте этот угол.","Сведите руки перед собой по дуге.","Разведите руки плавно, без чрезмерного растяжения."]'::jsonb,'["Разгибание локтей во время движения","Рывок корпусом"]'::jsonb),
('Тяга верхнего блока','lat-pulldown','спина','Тренажёр','machine_compound',120,'["Широчайшие"]'::jsonb,'["Бицепс","Ромбовидные"]'::jsonb,'Вертикальная тяга к груди с контролем лопаток.','["Зафиксируйте бёдра под валиком и возьмите рукоять.","Опустите плечи и направьте локти вниз.","Подтяните рукоять к верхней части груди.","Медленно верните руки вверх, сохраняя контроль."]'::jsonb,'["Тяга за голову","Раскачивание корпуса","Сильное отклонение назад"]'::jsonb),
('Тяга с упором грудью','chest-supported-row','спина','Гантели','compound',120,'["Ромбовидные","Широчайшие"]'::jsonb,'["Задняя дельта","Бицепс"]'::jsonb,'Горизонтальная тяга с опорой груди на наклонную скамью.','["Лягте грудью на наклонную скамью, стопы поставьте устойчиво.","Опустите руки с гантелями под плечами.","Подтяните гантели к рёбрам, сводя лопатки.","Опустите гантели плавно до выпрямления рук."]'::jsonb,'["Отрыв груди от скамьи","Подъём плеч к ушам"]'::jsonb),
('Тяга горизонтального блока','seated-cable-row','спина','Блок','machine_compound',120,'["Широчайшие","Ромбовидные"]'::jsonb,'["Бицепс","Задняя дельта"]'::jsonb,'Seated cable row — тяга сидя к поясу.','["Сядьте с немного согнутыми коленями и нейтральной спиной.","Удерживайте рукоять перед собой, опустите плечи.","Подтяните рукоять к животу, ведя локти назад.","Верните рукоять, не округляя поясницу."]'::jsonb,'["Раскачивание корпусом","Чрезмерный прогиб в пояснице"]'::jsonb),
('Жим гантелей сидя','seated-dumbbell-press','плечи','Гантели','compound',120,'["Дельтовидные"]'::jsonb,'["Трицепс","Верх груди"]'::jsonb,'Вертикальный жим с опорой спины.','["Сядьте на скамью с опорой спины, стопы прижмите к полу.","Поднимите гантели до уровня ушей.","Выжмите гантели вверх, не выгибая поясницу.","Опустите гантели контролируемо до исходного положения."]'::jsonb,'["Избыточный прогиб поясницы","Удар гантелями наверху"]'::jsonb),
('Подъём гантелей в стороны','lateral-raise','плечи','Гантели','isolation',75,'["Средняя дельта"]'::jsonb,'["Надостная мышца"]'::jsonb,'Отведение рук в стороны с умеренным весом.','["Встаньте устойчиво, держите гантели у бёдер.","Немного согните локти и поднимите руки в стороны.","Остановитесь около уровня плеч.","Медленно опустите гантели без раскачивания."]'::jsonb,'["Рывок ногами","Подъём плеч к ушам"]'::jsonb),
('Обратная бабочка','reverse-pec-deck','плечи','Тренажёр','isolation',75,'["Задняя дельта"]'::jsonb,'["Ромбовидные","Трапеция"]'::jsonb,'Разведение рук назад в тренажёре.','["Настройте сиденье так, чтобы рукояти были на уровне плеч.","Прижмите грудь к опоре и немного согните локти.","Разведите руки назад без рывка.","Верните рукояти медленно, удерживая грудь на опоре."]'::jsonb,'["Слишком большой вес","Переразгибание поясницы"]'::jsonb),
('Сгибание рук с гантелями','dumbbell-curl','бицепс','Гантели','isolation',75,'["Бицепс"]'::jsonb,'["Плечевая мышца","Предплечья"]'::jsonb,'Сгибание локтя с разворотом ладоней вверх.','["Встаньте устойчиво, расположите локти рядом с корпусом.","Поднимайте гантели, разворачивая ладони вверх.","Сократите бицепс без движения плечом вперёд.","Медленно разогните руки."]'::jsonb,'["Раскачивание корпуса","Выведение локтей вперёд"]'::jsonb),
('Молотковые сгибания','hammer-curl','бицепс','Гантели','isolation',75,'["Плечевая мышца","Бицепс"]'::jsonb,'["Плечелучевая мышца"]'::jsonb,'Hammer curl — сгибания с нейтральным хватом.','["Возьмите гантели ладонями друг к другу.","Зафиксируйте локти возле корпуса.","Согните руки, не меняя положение кистей.","Опустите гантели медленно."]'::jsonb,'["Залом кисти","Помощь корпусом"]'::jsonb),
('Разгибание рук на блоке','triceps-pushdown','трицепс','Блок','isolation',75,'["Трицепс"]'::jsonb,'["Предплечья"]'::jsonb,'Разгибание локтей с верхнего блока.','["Встаньте перед блоком и возьмитесь за рукоять.","Прижмите локти к бокам, держите плечи неподвижно.","Разогните руки вниз без резкого замыкания локтя.","Верните рукоять до комфортного сгибания."]'::jsonb,'["Движение плечами","Наклон всем весом на рукоять"]'::jsonb),
('Разгибание рук над головой','overhead-triceps-extension','трицепс','Блок','isolation',90,'["Трицепс"]'::jsonb,'["Мышцы корпуса"]'::jsonb,'Разгибание рук с канатом над головой.','["Повернитесь спиной к блоку и удерживайте канат над головой.","Сделайте устойчивый шаг вперёд и напрягите корпус.","Разогните локти, сохраняя плечи на месте.","Плавно верните канат за голову."]'::jsonb,'["Разведение локтей слишком широко","Прогиб в пояснице"]'::jsonb),
('Жим ногами','leg-press','квадрицепс','Тренажёр','machine_compound',150,'["Квадрицепс","Ягодичные"]'::jsonb,'["Приводящие мышцы"]'::jsonb,'Многосуставное разгибание ног в тренажёре.','["Прижмите спину и таз к опоре, стопы поставьте на платформу.","Снимите упоры и опустите платформу до комфортной глубины.","Следите, чтобы колени двигались в направлении носков.","Выжмите платформу, не замыкая колени рывком."]'::jsonb,'["Отрыв таза от опоры","Сведение коленей внутрь"]'::jsonb),
('Разгибание ног','leg-extension','квадрицепс','Тренажёр','isolation',75,'["Квадрицепс"]'::jsonb,'["Мышцы голени"]'::jsonb,'Изолированное разгибание коленей сидя.','["Совместите ось тренажёра с коленями.","Расположите валик над передней частью голеностопа.","Разогните ноги плавным движением.","Медленно опустите валик, не бросая вес."]'::jsonb,'["Рывок в начале","Отрыв таза от сиденья"]'::jsonb),
('Приседания с гантелью','goblet-squat','квадрицепс','Гантель','compound',120,'["Квадрицепс","Ягодичные"]'::jsonb,'["Мышцы корпуса","Приводящие мышцы"]'::jsonb,'Приседание с гантелью перед грудью.','["Держите гантель перед грудью, стопы поставьте устойчиво.","Согните колени и тазобедренные суставы, опуская таз.","Сохраняйте колени по направлению носков и опору всей стопой.","Встаньте без рывка, удерживая корпус стабильным."]'::jsonb,'["Отрыв пяток","Сведение коленей"]'::jsonb),
('Сгибание ног','leg-curl','бицепс бедра','Тренажёр','isolation',90,'["Задняя поверхность бедра"]'::jsonb,'["Икроножные"]'::jsonb,'Сгибание коленей в тренажёре.','["Отрегулируйте тренажёр под длину ног.","Расположите валик над пятками и зафиксируйте таз.","Согните колени до комфортного положения.","Разогните ноги медленно, сохраняя напряжение."]'::jsonb,'["Подъём таза","Резкое возвращение веса"]'::jsonb),
('Румынская тяга','romanian-deadlift','бицепс бедра','Штанга','compound',150,'["Задняя поверхность бедра","Ягодичные"]'::jsonb,'["Разгибатели спины","Предплечья"]'::jsonb,'Наклон с отведением таза и небольшим сгибанием коленей.','["Держите штангу у бёдер, колени немного согните.","Отведите таз назад, ведя гриф близко к ногам.","Опускайтесь до комфортного натяжения задней поверхности бедра.","Разогните тазобедренные суставы, сохраняя нейтральную спину."]'::jsonb,'["Округление поясницы","Отведение грифа от ног"]'::jsonb),
('Ягодичный мост со штангой','hip-thrust','ягодицы','Штанга','compound',120,'["Ягодичные"]'::jsonb,'["Задняя поверхность бедра","Мышцы корпуса"]'::jsonb,'Hip thrust — разгибание таза с опорой на скамью.','["Расположите верх спины на устойчивой скамье и защитную накладку на тазу.","Поставьте стопы так, чтобы голени наверху были близки к вертикали.","Поднимите таз, сокращая ягодицы.","Опустите таз под контролем, не переразгибая поясницу."]'::jsonb,'["Чрезмерный прогиб наверху","Неустойчивая скамья"]'::jsonb),
('Зашагивания на платформу','step-up','ягодицы','Гантели','high_intensity',120,'["Ягодичные","Квадрицепс"]'::jsonb,'["Задняя поверхность бедра","Мышцы корпуса"]'::jsonb,'Step-up — подъём на устойчивую платформу.','["Поставьте одну стопу целиком на платформу подходящей высоты.","Перенесите вес на переднюю ногу.","Поднимитесь усилием этой ноги, удерживая таз ровно.","Медленно опуститесь и выполните повторы другой ногой."]'::jsonb,'["Отталкивание нижней ногой","Потеря равновесия на высокой платформе"]'::jsonb),
('Подъёмы на носки стоя','standing-calf-raise','икры','Тренажёр','isolation',60,'["Икроножные"]'::jsonb,'["Камбаловидная мышца"]'::jsonb,'Calf raises — подошвенное сгибание стопы стоя.','["Расположите переднюю часть стоп на платформе.","Удерживайте колени мягкими и корпус стабильным.","Поднимитесь на носки и сделайте короткую паузу.","Медленно опустите пятки до комфортной амплитуды."]'::jsonb,'["Пружинящие движения","Завал стоп наружу"]'::jsonb),
('Подъёмы на носки сидя','seated-calf-raise','икры','Тренажёр','isolation',60,'["Камбаловидная мышца"]'::jsonb,'["Икроножные"]'::jsonb,'Подъём пяток с согнутыми коленями.','["Сядьте и расположите валики над коленями.","Поставьте переднюю часть стоп на платформу.","Поднимите пятки плавно, сохраняя опору носками.","Опустите пятки под контролем."]'::jsonb,'["Подбрасывание веса","Слишком короткая амплитуда"]'::jsonb),
('Скручивания на блоке','cable-crunch','core','Блок','isolation',60,'["Прямая мышца живота"]'::jsonb,'["Косые мышцы"]'::jsonb,'Сгибание корпуса с сопротивлением верхнего блока.','["Встаньте на колени перед блоком и удерживайте канат у головы.","Стабилизируйте таз и немного округлите верх спины.","Приблизьте рёбра к тазу за счёт мышц живота.","Вернитесь плавно, не вытягивая канат руками."]'::jsonb,'["Тяга руками","Сгибание только в тазобедренном суставе"]'::jsonb),
('Обратные скручивания','reverse-crunch','core','Коврик','isolation',60,'["Прямая мышца живота"]'::jsonb,'["Косые мышцы"]'::jsonb,'Подкручивание таза лёжа на спине.','["Лягте на спину, согните колени и прижмите руки к полу.","Подтяните колени к корпусу, слегка приподнимая таз.","Избегайте маха ногами и резких движений.","Медленно верните таз на коврик."]'::jsonb,'["Раскачивание ногами","Сильный прогиб поясницы"]'::jsonb);
INSERT INTO exercise_media(exercise_id,type,url,position) SELECT id,'image','/illustrations/' || CASE WHEN category IN ('грудь','трицепс') THEN 'push' WHEN category IN ('спина','бицепс','плечи') THEN 'pull' ELSE 'legs' END || '.svg',0 FROM exercises;

INSERT INTO workout_templates(id,user_id,name,description) VALUES ('22222222-2222-4222-8222-222222222221','11111111-1111-4111-8111-111111111111','Грудь + трицепс','Сильная база. Контроль в каждом повторении.');
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,0,3,8,12,default_rest_seconds FROM exercises WHERE slug='barbell-bench-press';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,1,3,10,12,default_rest_seconds FROM exercises WHERE slug='incline-dumbbell-press';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,2,3,10,12,default_rest_seconds FROM exercises WHERE slug='cable-fly';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,3,3,10,12,default_rest_seconds FROM exercises WHERE slug='triceps-pushdown';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,4,3,10,12,default_rest_seconds FROM exercises WHERE slug='overhead-triceps-extension';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222221',id,5,3,10,12,default_rest_seconds FROM exercises WHERE slug='cable-crunch';
INSERT INTO workout_templates(id,user_id,name,description) VALUES ('22222222-2222-4222-8222-222222222222','11111111-1111-4111-8111-111111111111','Спина + бицепс','Тяги, осанка и сила верхней части тела.');
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222222',id,0,3,8,12,default_rest_seconds FROM exercises WHERE slug='lat-pulldown';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222222',id,1,3,10,12,default_rest_seconds FROM exercises WHERE slug='chest-supported-row';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222222',id,2,3,10,12,default_rest_seconds FROM exercises WHERE slug='seated-cable-row';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222222',id,3,3,10,12,default_rest_seconds FROM exercises WHERE slug='dumbbell-curl';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222222',id,4,3,10,12,default_rest_seconds FROM exercises WHERE slug='hammer-curl';
INSERT INTO workout_templates(id,user_id,name,description) VALUES ('22222222-2222-4222-8222-222222222223','11111111-1111-4111-8111-111111111111','Ноги / общая силовая','Устойчивость и сила с первого шага.');
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,0,3,8,12,default_rest_seconds FROM exercises WHERE slug='leg-press';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,1,3,10,12,default_rest_seconds FROM exercises WHERE slug='leg-extension';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,2,3,10,12,default_rest_seconds FROM exercises WHERE slug='leg-curl';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,3,3,10,12,default_rest_seconds FROM exercises WHERE slug='hip-thrust';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,4,3,10,12,default_rest_seconds FROM exercises WHERE slug='step-up';
INSERT INTO workout_template_exercises(template_id,exercise_id,position,target_sets,target_reps_min,target_reps_max,rest_seconds) SELECT '22222222-2222-4222-8222-222222222223',id,5,3,10,12,default_rest_seconds FROM exercises WHERE slug='standing-calf-raise';

-- Explicit demo history; all statistics are computed from these completed sets.
DO $$
DECLARE i int; j int; sid uuid; seid uuid; tid uuid; ex record; n text; at timestamptz; w numeric; kcal numeric;
BEGIN
 FOR i IN 1..9 LOOP
  tid := ('22222222-2222-4222-8222-22222222222' || ((i-1)%3+1))::uuid;
  SELECT name INTO n FROM workout_templates WHERE id=tid;
  at := date_trunc('day',now()) - ((29-i*3) || ' days')::interval + interval '17 hours';
  INSERT INTO workout_sessions(user_id,template_id,name,started_at,finished_at,body_weight_kg,notes)
   VALUES ('11111111-1111-4111-8111-111111111111',tid,n,at,at+interval '62 minutes',86.4,'Демонстрационная тренировка') RETURNING id INTO sid;
  FOR ex IN SELECT te.*,e.category,e.calorie_class FROM workout_template_exercises te JOIN exercises e ON e.id=te.exercise_id WHERE te.template_id=tid ORDER BY te.position LOOP
   INSERT INTO workout_session_exercises(session_id,exercise_id,position,target_reps_min,target_reps_max,rest_seconds,started_at,finished_at)
    VALUES(sid,ex.exercise_id,ex.position,ex.target_reps_min,ex.target_reps_max,ex.rest_seconds,at+ex.position*interval '10 minutes',at+(ex.position+1)*interval '10 minutes') RETURNING id INTO seid;
   w := CASE WHEN ex.category='квадрицепс' AND ex.position=0 THEN 100 WHEN ex.category='core' THEN 20 WHEN ex.category IN ('бицепс','плечи') THEN 12.5 WHEN ex.calorie_class='isolation' THEN 25 WHEN ex.category='грудь' AND ex.position=0 THEN 65 ELSE 40 END + floor((i-1)/3)*2.5;
   FOR j IN 1..3 LOOP
    INSERT INTO workout_sets(session_exercise_id,set_number,weight_kg,reps,rir,rpe,completed,started_at,completed_at)
    VALUES(seid,j,w,12-j,2,8,true,at+(ex.position*600+j*150)*interval '1 second',at+(ex.position*600+j*150+40)*interval '1 second');
   END LOOP;
  END LOOP;
  SELECT (sum(40 * CASE e.calorie_class WHEN 'isolation' THEN 4 WHEN 'machine_compound' THEN 4.5 WHEN 'compound' THEN 5.5 ELSE 6 END * 1.1) + (3720-count(*)*40)*1.8)/60*3.5*86.4/200 INTO kcal
   FROM workout_sets ws JOIN workout_session_exercises se ON se.id=ws.session_exercise_id JOIN exercises e ON e.id=se.exercise_id WHERE se.session_id=sid;
  UPDATE workout_sessions SET estimated_calories=kcal WHERE id=sid;
 END LOOP;
 FOR i IN 0..7 LOOP
  INSERT INTO body_weight_entries(user_id,weight_kg,measured_at) VALUES('11111111-1111-4111-8111-111111111111',86.4+(7-i)*.15,now()-((7-i)*4 || ' days')::interval);
 END LOOP;
END $$;
